[[message]]
key = 'GREAT_PURPOSE_1'
old = 'エリアミッション《魔軍戦車カトブレパス》を攻略せよ！'
new = 'Clear Area Mission "Demon Army Tank Catoblepas"!'
[[message]]
key = 'GREAT_PURPOSE_2'
old = 'エピタフロード《英霊眠りし道 ラスニテ山麓》を攻略せよ！'
new = 'Clear the Epitaph Road "Path of Slumbering Heroes: Rathnite Foothills"!'
[[message]]
key = 'GREAT_PURPOSE_3'
old = 'サブストーリー《王家を救いし料理番》を支援せよ！'
new = 'Support Substory "Save the Royal Family Cook"!'
[[message]]
key = 'GREAT_PURPOSE_4'
old = 'ウォーミッション《ダクレイム砦奪還戦》を攻略せよ！'
new = 'Clear War Mission "Dacreim Fortress Recapture Battle"!'
[[message]]
key = 'GREAT_PURPOSE_5'
old = 'エリアミッション《古代の闇の中へ》を攻略せよ！'
new = 'Clear Area Mission "Into the Ancient Darkness"!'
[[message]]
key = 'GREAT_PURPOSE_6'
old = 'エピタフロード《英霊眠りし道 フェルヤナ荒原》を攻略せよ！'
new = 'Clear the Epitaph Road "英霊眠りし道 フェルヤナ荒原"!'
[[message]]
key = 'GREAT_PURPOSE_7'
old = 'サブストーリー《奪還を指揮せし異才者》を支援せよ！'
new = 'Support Substory "Rescue the Genius Commander"!'
[[message]]
key = 'GREAT_PURPOSE_8'
old = 'ウォーミッション《ジフール砦攻略戦》を攻略せよ！'
new = 'Clear War Mission "Jifule Fortress Capture Battle"!'
[[message]]
key = 'GREAT_PURPOSE_9'
old = 'エリアミッション《力に呑まれし王者》を攻略せよ！'
new = 'Clear Area Mission "力に呑まれし王者"!'
[[message]]
key = 'GREAT_PURPOSE_10'
old = 'エピタフロード《英霊眠りし道 メガドシスの記憶》を攻略せよ！'
new = 'Clear the Epitaph Road "英霊眠りし道 メガドシスの記憶"!'
[[message]]
key = 'GREAT_PURPOSE_11'
old = 'サブストーリー《暗部を暴きし暗躍者》を支援せよ！'
new = 'Support Substory "Expose the Dark Side to the One Operating behind the Scenes"!'
[[message]]
key = 'GREAT_PURPOSE_12'
old = 'ウォーミッション《霧の森の死闘》を攻略せよ！'
new = 'Clear War Mission "The Deathly Battle of the Forest of Mist"!'
[[message]]
key = 'GREAT_PURPOSE_13'
old = 'エリアミッション《彼方より堕ち呼ばれし魔道》を攻略せよ！'
new = 'Clear Area Mission "彼方より堕ち呼ばれし魔道"!'
[[message]]
key = 'GREAT_PURPOSE_14'
old = 'エピタフロード《英霊眠りし道 ウルテカの記憶》を攻略せよ！'
new = 'Clear the Epitaph Road "英霊眠りし道 ウルテカの記憶"!'
[[message]]
key = 'GREAT_PURPOSE_15'
old = ''
[[message]]
key = 'GREAT_PURPOSE_16'
old = 'ウォーミッション《蘇りし絶望の炎》を攻略せよ！'
new = 'Clear War Mission "Resurrection of the Flame of Despair"!'
