[[message]]
key = 'FUNC_SELECT_NAME_3'
old = 'ショップ'
new = 'Shop'
[[message]]
key = 'FUNC_SELECT_NAME_4'
old = 'ショップ'
new = 'Shop'
[[message]]
key = 'FUNC_SELECT_NAME_5'
old = 'ショップ'
new = 'Shop'
[[message]]
key = 'FUNC_SELECT_NAME_6'
old = 'ショップ'
new = 'Shop'
[[message]]
key = 'FUNC_SELECT_NAME_7'
old = '宿泊'
new = 'Inn'
[[message]]
key = 'FUNC_SELECT_NAME_8'
old = 'ショップ'
new = 'Shop'
[[message]]
key = 'FUNC_SELECT_NAME_9'
old = 'ショップ'
new = 'Shop'
[[message]]
key = 'FUNC_SELECT_NAME_10'
old = '戦技の付替え'
new = 'Arts Support'
[[message]]
key = 'FUNC_SELECT_NAME_11'
old = '転職／戦技の付替え'
new = 'Vocation / Arts Support'
[[message]]
key = 'FUNC_SELECT_NAME_12'
old = 'グランドミッション'
new = 'Grand Mission'
[[message]]
key = 'FUNC_SELECT_NAME_13'
old = 'パーティー編成'
new = 'Party Organization'
[[message]]
key = 'FUNC_SELECT_NAME_14'
old = 'クラン設立・加入'
new = 'Clan Management'
[[message]]
key = 'FUNC_SELECT_NAME_15'
old = 'クラフト'
new = 'Craft'
[[message]]
key = 'FUNC_SELECT_NAME_16'
old = '美容院'
new = 'Beauty Salon'
[[message]]
key = 'FUNC_SELECT_NAME_17'
old = 'レスタニアニュース'
new = 'Lestania News'
[[message]]
key = 'FUNC_SELECT_NAME_18'
old = '竜力の継承'
new = 'Dragon Force Augmentation'
[[message]]
key = 'FUNC_SELECT_NAME_19'
old = 'オーブ交換：クレスト'
new = 'Orb Exchange: Crests'
[[message]]
key = 'FUNC_SELECT_NAME_20'
old = 'オーブ交換：珍品／素材'
new = 'Orb Exchange: Rare Items / Materials'
[[message]]
key = 'FUNC_SELECT_NAME_21'
old = 'エリア情報'
new = 'Area Information'
[[message]]
key = 'FUNC_SELECT_NAME_22'
old = 'ジョブ修練'
new = 'Job Training'
[[message]]
key = 'FUNC_SELECT_NAME_24'
old = 'バザー'
new = 'Bazaar'
[[message]]
key = 'FUNC_SELECT_NAME_25'
old = ''
new = ''
[[message]]
key = 'FUNC_SELECT_NAME_26'
old = ''
new = ''
[[message]]
key = 'FUNC_SELECT_NAME_27'
old = ''
new = ''
[[message]]
key = 'FUNC_SELECT_NAME_28'
old = ''
new = ''
[[message]]
key = 'FUNC_SELECT_NAME_29'
old = ''
new = ''
[[message]]
key = 'FUNC_SELECT_NAME_30'
old = ''
new = ''
[[message]]
key = 'FUNC_SELECT_NAME_31'
old = ''
new = ''
[[message]]
key = 'FUNC_SELECT_NAME_32'
old = ''
new = ''
[[message]]
key = 'FUNC_SELECT_NAME_33'
old = ''
new = ''
[[message]]
key = 'FUNC_SELECT_NAME_34'
old = ''
new = ''
[[message]]
key = 'FUNC_SELECT_NAME_35'
old = ''
new = ''
[[message]]
key = 'FUNC_SELECT_NAME_36'
old = '報告書の確認'
new = 'Review Reports'
[[message]]
key = 'FUNC_SELECT_NAME_37'
old = 'ポーンの復活'
new = 'Revive Pawn'
[[message]]
key = 'FUNC_SELECT_NAME_39'
old = 'エクストリームミッション'
new = 'Extreme Missions'
[[message]]
key = 'FUNC_SELECT_NAME_40'
old = '復活力の回復'
new = 'Recover Revival Power'
[[message]]
key = 'FUNC_SELECT_NAME_41'
old = ''
new = ''
[[message]]
key = 'FUNC_SELECT_NAME_42'
old = 'ログインスタンプ'
new = 'Login Stamp'
[[message]]
key = 'FUNC_SELECT_NAME_43'
old = '報酬受け取り'
new = 'Receive Reward'
[[message]]
key = 'FUNC_SELECT_NAME_44'
old = 'トレジャーズロット'
new = 'Treasure Lot'
[[message]]
key = 'FUNC_SELECT_NAME_45'
old = '契約報酬の受け取り'
[[message]]
key = 'FUNC_SELECT_NAME_46'
old = '弱化の治療'
new = 'Treat Weakness'
[[message]]
key = 'FUNC_SELECT_NAME_47'
old = '戦徒の契り'
new = "Myrmidon's Pledge"
[[message]]
key = 'FUNC_SELECT_NAME_48'
old = '鑑定交換'
new = 'Appraisal Exchange'
[[message]]
key = 'FUNC_SELECT_NAME_49'
old = 'パートナーポーン'
new = 'Partner Pawn'
[[message]]
key = 'FUNC_SELECT_NAME_50'
old = '戦技の継承'
new = 'Skill Augmentation'
[[message]]
key = 'FUNC_SELECT_NAME_51'
old = 'アチーブメント'
new = 'Achievements'
[[message]]
key = 'FUNC_SELECT_NAME_52'
old = ''
new = ''
[[message]]
key = 'FUNC_SELECT_NAME_53'
old = 'ジョブ解放'
new = 'Vocation Unlock'
[[message]]
key = 'FUNC_SELECT_NAME_54'
old = 'ボックストレジャーズロット'
new = 'Box Treasure Lot'
[[message]]
key = 'FUNC_SELECT_NAME_55'
old = 'ポーン遠征隊'
new = 'Pawn Expedition Corps'
[[message]]
key = 'FUNC_SELECT_NAME_56'
old = '遠征結果の確認'
new = 'Confirm Expedition Results'
[[message]]
key = 'FUNC_SELECT_NAME_57'
old = 'プレイポイントショップ'
new = 'Play Point Shop'
[[message]]
key = 'FUNC_SELECT_NAME_58'
old = 'クラン拠点管理'
new = 'Clan Hall Management'
[[message]]
key = 'FUNC_SELECT_NAME_59'
old = '戦技練習'
new = 'Warfare Practice'
[[message]]
key = 'FUNC_SELECT_NAME_60'
old = 'クランダンジョン'
new = 'Clan Dungeon'
[[message]]
key = 'FUNC_SELECT_NAME_61'
old = 'プレゼント'
new = 'Present'
[[message]]
key = 'FUNC_SELECT_NAME_62'
old = 'プレゼント状況確認'
new = 'Present Status Check'
[[message]]
key = 'FUNC_SELECT_NAME_63'
old = 'プレゼント状況確認'
new = 'Present Status Check'
[[message]]
key = 'FUNC_SELECT_NAME_64'
old = '絶技の継承'
new = 'Special Skill Augmentation'
[[message]]
key = 'FUNC_SELECT_NAME_65'
old = 'ジョブエンブレム'
new = 'Vocation Emblem'
[[message]]
key = 'FUNC_SELECT_NAME_66'
old = 'サブストーリーログ'
new = 'Substory Log'
[[message]]
key = 'FUNC_SELECT_NAME_67'
old = '英霊眠りし道'
new = 'Path of Slumbering Heroes'
[[message]]
key = 'FUNC_SELECT_NAME_68'
old = '魂を捧げる'
new = 'Give Spirits'
[[message]]
key = 'FUNC_SELECT_NAME_69'
old = 'ウォーミッション'
new = 'War Missions'
[[message]]
key = 'FUNC_SELECT_NAME_70'
old = 'ドミニオンポイントショップ'
new = 'Dominion Point Shop'
[[message]]
key = 'FUNC_SELECT_NAME_71'
old = '転生'
new = 'Reincarnation'
[[message]]
key = 'FUNC_SELECT_NAME_72'
old = '武具のカスタムメイド'
new = 'Custom-made Arms'
[[message]]
key = 'FUNC_SELECT_NAME_73'
old = '武具の資源分解'
new = 'Arms Resource Disassembly'
[[message]]
key = 'FUNC_SELECT_NAME_74'
old = '冒パスショップ'
new = 'Adventure Pass Shop'
[[message]]
key = 'FUNC_SELECT_NAME_75'
old = 'Lv.80にする'
new = 'Become Lv.80'
[[message]]
key = 'FUNC_SELECT_NAME_76'
old = '竜力の継承を埋める'
new = 'Complete Augmentation of Dragon Force'
[[message]]
key = 'FUNC_SELECT_NAME_77'
old = '冒険をしやすくする'
new = 'Make Adventure Easier'
[[message]]
key = 'FUNC_SELECT_NAME_78'
old = 'アチーブメント：王家再興'
new = 'Achievements: Royal Family Restoration'
[[message]]
key = 'FUNC_SELECT_NAME_80'
old = '紋章メダル交換'
new = 'Emblem Medal Exchange'
[[message]]
key = 'FUNC_SELECT_NAME_81'
old = 'おでかけ支援サービス'
new = 'Outing Support Service'
[[message]]
key = 'FUNC_SELECT_NAME_82'
old = '他人の自室訪問'
new = "Visit Another's Room"
[[message]]
key = 'FUNC_SELECT_NAME_83'
old = ''
new = ''
[[message]]
key = 'FUNC_SELECT_NAME_84'
old = 'プレゼント報酬確認'
new = 'Present Reward Review'
[[message]]
key = 'FUNC_SELECT_NAME_85'
old = '自室訪問設定'
new = 'My Room Visit Setup'
[[message]]
key = 'FUNC_SELECT_NAME_86'
old = '冒険ガイド'
new = 'Adventure Guide'
[[message]]
key = 'FUNC_SELECT_NAME_87'
old = '募集掲示板'
new = 'Recruitment Board'
[[message]]
key = 'FUNC_SELECT_NAME_88'
old = '黒呪装具の効果封印'
new = 'Bitterblack Equipment Effect Seal'
[[message]]
key = 'FUNC_SELECT_NAME_89'
old = 'レアアイテムの鑑定'
new = 'Rare Item Appraisal'
[[message]]
key = 'FUNC_SELECT_NAME_90'
old = '黒呪アイテムの持ち帰り'
new = 'Bitterblack Item Takeaway'
[[message]]
key = 'FUNC_SELECT_NAME_91'
old = '探索結果の報告'
new = 'Report Search Results'
[[message]]
key = 'FUNC_SELECT_NAME_93'
old = 'Lv.85にする（仮）'
new = 'Become Lv.85 (Provisional)'
[[message]]
key = 'FUNC_SELECT_NAME_94'
old = 'ジョブ修練スキップ（仮）'
new = 'Job Training Skip (Provisional)'
[[message]]
key = 'FUNC_SELECT_NAME_95'
old = '印記章交換'
new = 'Medal Exchange'
[[message]]
key = 'FUNC_SELECT_NAME_96'
old = '大口納品イベント'
new = 'Large Delivery Event'
[[message]]
key = 'FUNC_SELECT_NAME_97'
old = '黒呪ショップ'
new = 'Bitterblack Shop'
[[message]]
key = 'FUNC_SELECT_NAME_98'
old = '進行のリセット'
new = 'Reset Progress'
[[message]]
key = 'FUNC_SELECT_NAME_99'
old = 'ワイルドハント'
new = 'Wild Hunt'
[[message]]
key = 'FUNC_SELECT_NAME_100'
old = 'ハイオーブ交換'
new = 'High Orb Exchange'
[[message]]
key = 'FUNC_SELECT_NAME_101'
old = 'ドラゴンアビリティの合成'
new = 'Dragon Ability Synthesis'
[[message]]
key = 'FUNC_SELECT_NAME_102'
old = '竜防具の鑑定交換'
new = 'Dragon Armor Appraisal'
[[message]]
key = 'FUNC_SELECT_NAME_103'
old = 'リワードミッション'
new = 'Reward Mission'
[[message]]
key = 'FUNC_SELECT_NAME_104'
old = 'リワードメダル交換'
new = 'Reward Medal Exchange'
