default_format = {proper = true}
[[message]]
key = 'LAND_NAME_1'
old = 'レスタニア'
new = 'Lestania'
[[message]]
key = 'LAND_NAME_2'
old = '魔赤島'
new = 'Bloodbane Isle'
[[message]]
key = 'LAND_NAME_3'
old = 'フィンダム'
new = 'Phindym'
[[message]]
key = 'LAND_NAME_4'
old = 'アッカーシェラン'
new = 'Acre Selund'
[[message]]
key = 'LAND_NAME_5'
old = '英霊眠りし道'
new = 'Path of Slumbering Heroes'
[message.format]
proper = false
[[message]]
key = 'LAND_NAME_6'
old = '黒呪の迷宮'
new = 'Bitterblack Maze'
[[message]]
key = 'LAND_NAME_7'
old = '闇大陸：レスタニア'
new = 'Dark Continent: Lestania'
[[message]]
key = 'LAND_NAME_10'
old = '闇大陸：フィンダム'
new = 'Dark Continent: Phindym'
[[message]]
key = 'LAND_NAME_11'
old = '闇大陸：アッカーシエラン'
new = 'Dark Continent: Acre Selund'
[[message]]
key = 'LAND_NAME_12'
old = '闇大陸：メルゴダ'
new = 'Dark Continent: Mergoda'
