default_format = {proper = false}
[[message]]
key = 'SPOT_NAME_'
old = 'フェルヤナ荒原'
new = 'Feryana Wilderness'
[[message]]
key = 'SPOT_NAME_'
old = 'メフィテ'
new = 'Mephite'
[[message]]
key = 'SPOT_NAME_'
old = '展望城'
new = 'Lookout Castle'
[[message]]
key = 'SPOT_NAME_'
old = '最果ての岸'
new = 'Farthest Bank'
[[message]]
key = 'SPOT_NAME_'
old = 'オジナの支配圏'
new = "Ogina's Domination Area"
[[message]]
key = 'SPOT_NAME_'
old = '魔軍進行中継場'
[[message]]
key = 'SPOT_NAME_'
old = '嘆きの湿原'
new = 'Wailing Wetland'
[[message]]
key = 'SPOT_NAME_'
old = '大門前野営地'
[[message]]
key = 'SPOT_NAME_'
old = '銀隠者の根城'
new = "Silver Hermit's Stronghold"
[[message]]
key = 'SPOT_NAME_'
old = '軍鬼の哨戒地'
new = "Army Demon's Patrol Ground"
[[message]]
key = 'SPOT_NAME_'
old = '軍妖鳥の関所'
new = "Army Demon Bird's Checkpoint"
[[message]]
key = 'SPOT_NAME_'
old = '秘泉への暗道'
new = 'Dark Path to the Secret Spring'
[[message]]
key = 'SPOT_NAME_'
old = '劫炎の祠堂'
new = 'Shrine of the Eternal Blaze'
[[message]]
key = 'SPOT_NAME_'
old = '王家の隠れ道'
new = "Royal Family's Secret Path"
[[message]]
key = 'SPOT_NAME_'
old = 'いつわりの遺構'
new = 'False Remains'
[[message]]
key = 'SPOT_NAME_'
old = '安息無き地下水道'
new = 'Restless Water Channel'
[[message]]
key = 'SPOT_NAME_'
old = '英霊眠りし道　フェルヤナ荒原'
new = 'Path of Slumbering Heroes: Feryana Wilderness'
[[message]]
key = 'SPOT_NAME_'
old = '古テキア洞窟'
new = 'Old Tekia Grotto'
[[message]]
key = 'SPOT_NAME_'
old = '轟咆洞'
new = 'Thundering Roar Cave'
