default_format = {proper = false}
[[message]]
key = 'SPOT_NAME_'
old = 'ラスニテ山麓'
new = 'Rathnite Foothills'
[[message]]
key = 'SPOT_NAME_'
old = 'ラスニテ山麓　湖畔部'
new = 'Rathnite Foothills Lakeside'
[[message]]
key = 'SPOT_NAME_'
old = '隠れ村ピレモス'
new = 'Hidden Village Piremoth'
[[message]]
key = 'SPOT_NAME_'
old = 'ティネス砦'
new = 'Fort Thines'
[message.format]
proper = true
[[message]]
key = 'SPOT_NAME_'
old = 'ロスギル'
new = 'Rothgill'
[message.format]
proper = true
[[message]]
key = 'SPOT_NAME_'
old = 'ベルタ盗賊団のアジト'
new = "Bertha's Bandit Group Hideout"
[message.format]
proper = true
[[message]]
key = 'SPOT_NAME_'
old = '小鬼の物見台'
new = 'Goblin Lookout'
[[message]]
key = 'SPOT_NAME_'
old = '遠吠えの前線'
new = 'The Howling Front'
[message.format]
new = 'Howling Front'
[[message]]
key = 'SPOT_NAME_'
old = '廃村デニスィル'
new = 'Deserted Village of Denisyr'
[[message]]
key = 'SPOT_NAME_'
old = '休憩所跡地'
new = 'Former Rest Station'
[[message]]
key = 'SPOT_NAME_'
old = '落露の大穴'
new = 'Dewdrop Crater'
[[message]]
key = 'SPOT_NAME_'
old = 'フェルヤナ関所前'
new = 'Feryana Border Checkpoint'
[[message]]
key = 'SPOT_NAME_'
old = '魔軍戦車駐留地'
new = 'Demon Army War Machine Garrison'
[[message]]
key = 'SPOT_NAME_'
old = '魔軍緊急野営地'
new = 'Demon Army Camp'
[[message]]
key = 'SPOT_NAME_'
old = '獣将の園生'
new = "Beastmaster's Garden"
[[message]]
key = 'SPOT_NAME_'
old = '冥府下りの洞穴'
new = "Cave of Hell's Descent"
[[message]]
key = 'SPOT_NAME_'
old = 'ラスニテ地下水路'
new = 'Rathnite Underground Waterway'
[[message]]
key = 'SPOT_NAME_'
old = '湖畔の洞窟'
new = 'Lakeside Grotto'
[[message]]
key = 'SPOT_NAME_'
old = 'イミズディット遺跡'
new = 'Yimidhitt Ruins'
[[message]]
key = 'SPOT_NAME_'
old = 'ウルタ古水路'
new = 'Ulta Ancient Watercourse'
[[message]]
key = 'SPOT_NAME_'
old = '英霊眠りし道　ラスニテ山麓'
new = 'Path of Slumbering Heroes: Rathnite Foothills'
[[message]]
key = 'SPOT_NAME_'
old = 'ラスニテ納骨廟'
new = 'Rathnite Columbarium'
